apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: retail-app
spec:
  type: ExternalName
  externalName: project-bedrock-mysql.cmv8ggwc27f0.us-east-1.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: retail-app
spec:
  type: ExternalName
  externalName: project-bedrock-postgresql.cmv8ggwc27f0.us-east-1.rds.amazonaws.com
